language: julia
os:
  - linux
julia:
  - 0.6
  - nightly
notifications:
  email: false
#script: # the default script is equivalent to the following
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("Survival"); Pkg.test("Survival"; coverage=true)';
after_success:
  - julia -e 'cd(Pkg.dir("Survival")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';
